// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn-GKZzAm15ScXtBc08XMvF1TMQpQ_StQ',
    appId: '1:369284581787:web:a4bec37c8f94ad1b2af93e',
    messagingSenderId: '369284581787',
    projectId: 'conductor-app-daf91',
    authDomain: 'conductor-app-daf91.firebaseapp.com',
    storageBucket: 'conductor-app-daf91.firebasestorage.app',
    measurementId: 'G-X5SLPR4BJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7s504DKg-1FdvXm6NeY2vBkoJNWX5rhQ',
    appId: '1:369284581787:android:1e26a75ce7324c282af93e',
    messagingSenderId: '369284581787',
    projectId: 'conductor-app-daf91',
    storageBucket: 'conductor-app-daf91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHJrs7JhpYbief6rXaFthDjOoVtdtU0IY',
    appId: '1:369284581787:ios:261294e9c18dfd9d2af93e',
    messagingSenderId: '369284581787',
    projectId: 'conductor-app-daf91',
    storageBucket: 'conductor-app-daf91.firebasestorage.app',
    iosBundleId: 'com.example.conductorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHJrs7JhpYbief6rXaFthDjOoVtdtU0IY',
    appId: '1:369284581787:ios:261294e9c18dfd9d2af93e',
    messagingSenderId: '369284581787',
    projectId: 'conductor-app-daf91',
    storageBucket: 'conductor-app-daf91.firebasestorage.app',
    iosBundleId: 'com.example.conductorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn-GKZzAm15ScXtBc08XMvF1TMQpQ_StQ',
    appId: '1:369284581787:web:a09c44d7311063dc2af93e',
    messagingSenderId: '369284581787',
    projectId: 'conductor-app-daf91',
    authDomain: 'conductor-app-daf91.firebaseapp.com',
    storageBucket: 'conductor-app-daf91.firebasestorage.app',
    measurementId: 'G-352E14JFCS',
  );

}